//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoID { get; set; }
        public Nullable<int> VentaID { get; set; }
        public Nullable<int> MetodoPagoID { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
    
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
