//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosCelulares.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoReparacion
    {
        public int ProductoReparacionID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> ReparacionID { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Reparacione Reparacione { get; set; }
    }
}
