//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosCelulares.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Reparacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparacione()
        {
            this.ProductoReparacions = new HashSet<ProductoReparacion>();
        }
    
        public int ReparacionID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> CelularReparacionID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string ProblemaReportado { get; set; }
        public string EstadoReparacion { get; set; }
        public Nullable<decimal> CostoReparacion { get; set; }
    
        public virtual CelularReparacion CelularReparacion { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoReparacion> ProductoReparacions { get; set; }
    }
}
